const data = [
  {
    img: "/img/card/image 33.png",
    icon: "/img/Vector.png",
    title: "Swiss Apls",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 1,
  },
  {
    img: "/img/card/image 34.png",
    icon: "/img/Vector.png",
    title: "Hallstatt",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 2,
  },
  {
    img: "/img/card/image 35.png",
    icon: "/img/Vector.png",
    title: "Faroe Island",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 3,
  },
  {
    img: "/img/card/image 36.png",
    icon: "/img/Vector.png",
    title: "Innsbruck",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 4,
  },
  {
    img: "/img/card/image 32.png",
    icon: "/img/Vector.png",
    title: "Val di Funes",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 5,
  },
  {
    img: "/img/card/image 31.png",
    icon: "/img/Vector.png",
    title: "Ushuaia",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 6,
  },
  {
    img: "/img/card/image 30.png",
    icon: "/img/Vector.png",
    title: "Berchtesgaden",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 7,
  },
  {
    img: "/img/card/image 29.png",
    icon: "/img/Vector.png",
    title: "Mauritius",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 8,
  },
  {
    img: "/img/card/image 28.png",
    icon: "/img/Vector.png",
    title: "Havelock",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 9,
  },
  {
    img: "/img/card/image 27.png",
    icon: "/img/Vector.png",
    title: "Whitsunday Islands",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 10,
  },
  {
    img: "/img/card/image 26.png",
    icon: "/img/Vector.png",
    title: "Innsbruck",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 11,
  },
  {
    img: "/img/card/image 25.png",
    icon: "/img/Vector.png",
    title: "Innsbruck",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 12,
  },
  {
    img: "/img/card/image 24.png",
    icon: "/img/Vector.png",
    title: "Innsbruck",
    p: "3Days 4 Nights",
    price: "₹88,952",
    person: "Per person",
    id: 13,
  },
];

export default data;
